use evidence collection v2 in unit/acceptance test

diff --git a/.one-pipeline.yaml b/.one-pipeline.yaml
--- a/.one-pipeline.yaml
+++ b/.one-pipeline.yaml
@@ -21,7 +21,24 @@ test:
 
     cd ../"$(load_repo app-repo path)"
     npm ci
-    npm test
+    
+    # save exit code for old evidence collection
+    exit_code=0
+    npm test || exit_code=$?
+    
+    # save status for new evidence collection
+    status="success"
+    if [ "$exit_code" != "0" ]; then
+      status="failure"
+    fi
+    
+    collect-evidence \
+      --tool-type "jest" \
+      --status "$status" \
+      --evidence-type "com.ibm.unit_tests" \
+      --asset-type "repo" \
+      --asset-key "app-repo"
+    exit $exit_code
 
 containerize:
   dind: true
@@ -72,7 +89,24 @@ acceptance-test:
     source /root/.nvm/nvm.sh
     npm ci
     export APP_URL=$(cat ../app-url)
-    npm run acceptance-test
+    
+    # save exit code for old evidence collection
+    exit_code=0
+    npm run acceptance_test || exit_code=$?
+    
+    # save status for new evidence collection
+    status="success"
+    if [ "$exit_code" != "0" ]; then
+      status="failure"
+    fi
+    
+    collect-evidence \
+      --tool-type "jest" \
+      --status "$status" \
+      --evidence-type "com.ibm.acceptance_tests" \
+      --asset-type "repo" \
+      --asset-key "app-repo"
+    exit $exit_code
 
 release:
   abort_on_failure: false
